### ISSUE TITLE
A question about when a piece of code is triggered

### ISSUE THREAD

**Issue by rainbowfart918** [Jacyhust/LSH-APG#1]
Hi！
I want to know when the code in the screenshot below will be triggered.When I change the insertion method, this will trigger, but I don't know where the problem is because the modified program does not trigger this error every time it runs, and it occurs approximately once every two to three runs.
![image](https://github.com/Jacyhust/LSH-APG/assets/158448829/abb881f8-4446-4fb7-b9a6-b06d95906b5d)
Looking forward to your response, thank you！

**Comment by Jacyhust** [comment]
Can you inform how you changed the insertion method? This part of code is used for checking whether there are duplicated edges in the graph. If so, the graph is wrongly built.

**Comment by rainbowfart918** [comment]
> Can you inform how you changed the insertion method? This part of code is used for checking whether there are duplicated edges in the graph. If so, the graph is wrongly built.

I replied to you in the email, but you may not have paid attention to it, this problem has been resolved.
But I have a new question. Why did you mention in your paper that your method is slightly faster than HNSW? However, when I tested the deep1M dataset and set k=100, I found that your method is not as fast as the knnHNSW in your divgraph. What's going on? Except for k, it's all the default parameters you set

**Comment by rainbowfart918** [comment]
> Can you inform how you changed the insertion method? This part of code is used for checking whether there are duplicated edges in the graph. If so, the graph is wrongly built.
I replied to you in the email, but you may not have noticed, but fortunately the problem has been resolved
But I have a new question. Why did you mention in your paper that your method is slightly faster than HNSW? However, when I tested the audio dataset and set k=100, I found that your method is not as fast as the knnHNSW in your divgraph. What's going on? Except for k, it's all the default parameters you set
![image](https://github.com/Jacyhust/LSH-APG/assets/158448829/bb6e95fd-4ad2-4cd6-a17c-b6bcc657a0b8)

**Comment by rainbowfart918** [comment]
> Can you inform how you changed the insertion method? This part of code is used for checking whether there are duplicated edges in the graph. If so, the graph is wrongly built.
